### ISSUE TITLE
ConfigureAwait?

### ISSUE THREAD

**Issue by danielwertheim** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#301]
Unfortunately I'm in the position where I need to make a blocking call (`foo.Result`) and in the chain underneath, the `ConfigurationManager.GetAsync` method is used with `await` and `ConfigureAwait(false)` but I do experience some deadlocks (which goes away when not using `ConfigurationManager` but other async retrieving components).

Could this be, since you don't use `ConfigureAwait(false)` e.g. here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocol.Extensions/Configuration/ConfigurationManager.cs#L170

**Comment by brentschmaltz** [comment]
@danielwertheim we put the ConfigureAwait(false) on HttpDocumentRetriever https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L88

Are you are saying every 'await' in the chain needs .ConfigureAwait(false) ?

**Comment by danielwertheim** [comment]
I was trying both the GenericDocumentRetriever´and the HttpDocumentRetriver. Btw...

Blocking call? Why?

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L79

**Comment by brentschmaltz** [comment]
We chose to block to check the Response code.

**Comment by danielwertheim** [comment]
Yes, but there's no need to do a blocking call there since you are in an async context. Just await it. Get the response. Check the status on it and continue the flow.

```
var response = await _httpClient.GetAsync(address, cancel).ConfigureAwait(false);
response.EnsureSuccessStatusCode();
```

I usually have an extension method for the `ConfigureAwait....`

```
    public static class TaskExtensions
    {
        public static ConfiguredTaskAwaitable<T> ForAwait<T>(this Task<T> t)
        {
            return t.ConfigureAwait(false);
        }
    }
```

Can also make that one return the `Task<T>` instead if you want.

Then

```
var response = await _httpClient.GetAsync(address, cancel).ForAwait();
response.EnsureSuccessStatusCode();
```

**Comment by brentschmaltz** [comment]
@danielwertheim I think your point about not blocking is valid and we can fix this in RC2.
I don't want to add the extension method as in a framework I try to keep extension methods at a minimum. Are you OK with this?

**Comment by danielwertheim** [comment]
Sounds good.

**Comment by brentschmaltz** [comment]
@danielwertheim We pushed a fix to our 4x release on MyGet. We have a couple of additional fixes before we push out to nuget.org

**Comment by skottmckay** [comment]
Shouldn't the WaitAsync() on _refreshLock in ConfigurationManager.cs also have the ConfigureAwait(false)? I would have expected all 'await' statements to use that unless you have a reason not to. Otherwise you still have the potential for deadlock.
