### ISSUE TITLE
InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://DevIDPServer/sts/Metadata.xml'

### ISSUE THREAD

**Issue by arc2018** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#804]
I get this error when start the application. it is not able to complete the configuration from Federation Metadata. if I enter the metadata url on the browser I am able to see the xml, but only issue I see is that there is  a certificate error, which I override on the browser. would that be an issue causing this?

my config:
` public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddAuthentication(sharedOptions =>
                        {
                            sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
                        })
                       .AddWsFederation(options =>
                       {
                           options.Wtrealm = @"http://localhost:3230/";// Configuration["wsfed:realm"];
                           options.MetadataAddress = @"https://DevIDPServer/sts/Metadata.xml";// Configuration["wsfed:metadata"];
                       })
                       .AddCookie();

        }
`

` app.UseAuthentication();`

----------------------Errors-----------------------------

`System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://DevIDPServer/sts/Metadata.xml'. ---> Microsoft.IdentityModel.Xml.XmlReadException: IDX13004: Security token type role descriptor is expected.
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadEntityDescriptor(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadMetadata(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleChallengeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<ChallengeAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

**Comment by arc2018** [comment]
oops..looks like I posted it in the wrong place...

**Comment by Tratcher** [comment]
@brentschmaltz any idea why you'd get a XmlReadException for an https failure?

**Comment by arc2018** [comment]
@Tratcher  thank you for your response.
I added the BackchannelHttpHandler,  but that did not make any difference, I get the same error. It does not look an issue due to the certificate error. it show a different error related security when I return false in the ServerCertificateCustomValidationCallback 
this is the new code:
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddAuthentication(sharedOptions =>
                        {
                            sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
                        })
                       .AddWsFederation(options =>
                       {
                           options.Wtrealm = @"http://localhost:3230/";// Configuration["wsfed:realm"];
                           options.MetadataAddress = @"https://DevIDPServer/sts/Metadata.xml";// Configuration["wsfed:metadata"];
                           options.BackchannelHttpHandler = new HttpClientHandler() {
                               ServerCertificateCustomValidationCallback =
                               (req, cert, er, t) =>
                                 true
                           };
                       })
                       .AddCookie();

        }
`
I created a test 4.5 app pointing to the same IDP and it works without any issue on the same machine. here is my web config on the 4.5 machine. We are using SecureAuth as our identity provider.

`<system.identityModel>
    <identityConfiguration>
      <audienceUris>
        <add value="http://localhost/testAuth/" />
      </audienceUris>
      <certificateValidation certificateValidationMode="None" />
      <issuerNameRegistry type="System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
        <trustedIssuers>
          <add thumbprint="22 33 s3 57 cd aa d3 a3 07 ea 32 7s e6 b9 ec e3 84 7d 91 34" name="https://DevIDPServer/sts/" />
        </trustedIssuers>
      </issuerNameRegistry>
    </identityConfiguration>
  </system.identityModel>
  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" hideFromScript="true" persistentSessionLifetime="1:2:0" />
      <wsFederation passiveRedirectEnabled="true" persistentCookiesOnPassiveRedirects="true" issuer="https://DevIDPServer/sts/" realm="http://localhost/testAuth/" reply="http://localhost/testAuth/" requireHttps="false" />
    </federationConfiguration>
  </system.identityModel.services>`

**Comment by brentschmaltz** [comment]
@arc2018 can you post the wsFed metadata xml. 
This statement 
`Microsoft.IdentityModel.Xml.XmlReadException: IDX13004: Security token type role descriptor is expected.`

indicates the xml is not as expected. We are expecting at least one 'RoleDescriptor'

**Comment by arc2018** [comment]
@brentschmaltz   thank you for your help. I am attaching metadata.xml

[Metadata_xml.txt](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/1404356/Metadata_xml.txt)

**Comment by brentschmaltz** [comment]
@arc2018 the issue is our code expects to find a <RoleDescriptor xsi:type="fed:SecurityTokenServiceType"  ... which is where we will look for keys.

We could relax this, as it's optional

**Comment by brentschmaltz** [comment]
fixed commit https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/79be3ea38fc5f5e18c4f4e4a90857162f456ebb8

**Comment by ryanbuening** [comment]
@brentschmaltz I'm also getting this error: `IDX13004: Security token type role descriptor is expected.` Is there an updated build I can grab to test your fix? Thanks.

**Comment by ryanbuening** [comment]
Is it possible for me to add a `<RoleDescriptor>` tag to my `metadata.xml` file to bypass the `Security token type role descriptor is expected.` error I'm getting until a fix is released?

**Comment by ryanbuening** [comment]
@arc2018 were you able to get your implementation working with the `preview2` release?: https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation/

I'm able to get past the `Security token type role descriptor is expected.` error now, but still not successful in getting a cookie.

My 4.5 `web.config` looked similar to yours with the `persistentCookiesOnPassiveRedirects="true"` and  `passiveRedirectEnabled="true"`. I'm using PortalGuard. I didn't know if/how I need to account for those in a .NET Core implementation.

## 4.5 web.config
```xml
<system.identityModel>
	<identityConfiguration>
		<securityTokenHandlers>
			<remove type="System.IdentityModel.Tokens.SessionSecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=abc123" />
			<add type="System.IdentityModel.Services.Tokens.MachineKeySessionSecurityTokenHandler, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=abc123" />
			<add type="System.IdentityModel.Tokens.Saml2SecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=abc123">
				<samlSecurityTokenRequirement mapToWindows="false"></samlSecurityTokenRequirement>
			</add>
		</securityTokenHandlers>
		<audienceUris>
			<add value="https://auth.domain.com/" />
		</audienceUris>
		<issuerNameRegistry type="System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
			<trustedIssuers>
				<add thumbprint="abc123" name="https://saml.domain.com:1234/sso/" />
			</trustedIssuers>
		</issuerNameRegistry>
	</identityConfiguration>
</system.identityModel>
<system.identityModel.services>
	<federationConfiguration>
		<wsFederation persistentCookiesOnPassiveRedirects="true"passiveRedirectEnabled="true" issuer="https://saml.domain.com:1234/sso/go.ashx" realm="https://auth.domain.com/" requireHttps="false" />
		<cookieHandler requireSsl="false" path="/" domain="domain.com" persistentSessionLifetime="0:8:0:0"></cookieHandler>
	</federationConfiguration>
</system.identityModel.services>
```

## metadata.xml

```xml
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://saml.domain.com:1234/idp/identifier">
	<IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
		<KeyDescriptor use="signing">
			<KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
				<X509Data>
					<X509Certificate>abc123=</X509Certificate>
				</X509Data>
			</KeyInfo>
		</KeyDescriptor>
		<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
		</NameIDFormat>
		<NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
		</NameIDFormat>
		<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://saml.domain.com:1234/sso/go.ashx"/>
		<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://saml.domain.com:1234/sso/go.ashx"/>
	</IDPSSODescriptor>
	<ContactPerson contactType="support"/>
</EntityDescriptor>
```

## .NET Core Startup.cs
```csharp
services.AddAuthentication(sharedOptions =>
{
	sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
})
.AddWsFederation(options =>
{
	options.Wtrealm = "https://auth.domain.com";
	options.MetadataAddress = "https://saml.domain.com:1234/sso/metadata.xml";
})
.AddCookie(options =>
{
	//options.LoginPath = "/api/login"; // not sure if needed?
	//options.LogoutPath = "/api/logout"; // not sure if needed?
});
```

However, when I load my project, I get a `404` and the URL is: `https://auth.domain.com/myappdirectory?wtrealm=https%3A%2F%2Fauth.domain.com%2F&wa=wsignin1.0&wreply=https%3A%2F%2Fauth.domain.com%2Fmyappdirectory%2Fsignin-wsfed&wctx=GUIDHere`

The logs have the following warnings:

- warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
- warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
- warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {12076a57-7f06-4639-9865-965be6d5df32} may be persisted to storage in unencrypted form.
- The sign-out redirect URI [url here] is malformed
